// Image data for AMV VERSE
const images = [
  "a-couple-of-cuckoos-season-2-card.jpg",
  "a-couple-of-cuckoos-card.jpg",
  "a-silent-voice-card.jpg",
  "alya-sometimes-hides-her-feelings-in-russian-card.jpg",
  "ameku-md-doctor-detective-card.jpg",
  "attack-on-titan-season-2-card.jpg",
  "attack-on-titan-card.jpg",
  "battle-through-the-heavens-card.jpg",
  "blue-lock-movie-episode-nagi-card.jpg",
  "dan-da-dan-season-2-card.jpg",
  "dan-da-dan-card.jpg",
  "demon-slayer-mugen-train-card.jpg",
  "eclipse-of-illusion-card.jpg",
  "fragrant-flower-blooms-with-dignity-card.jpg",
  "garden-of-words-card.jpg",
  "hello-world-card.jpg",
  "honey-lemon-soda-card.jpg",
  "horimiya-the-missing-piece-card.jpg",
  "horimiya-the-missing-piece-season-2-card.jpg",
  "im-getting-married-to-a-girl-i-hate-card.jpg",
  "jujutsu-kaisen-0-card.jpg",
  "jujutsu-kaisen-2-card.jpg",
  "jujutsu-kaisen-card.jpg"
];